// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // now the seed is triggered with command 'npx prisma db seed'
    seed: "tsx -r dotenv/config prisma/seed.ts"
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
